/*
 * This file is generated by jOOQ.
 */
package com.jooq.shop.enity;


import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shop implements Serializable {

    private static final long serialVersionUID = 458818163;

    private Integer       id;
    private String        shopName;
    private String        desc;
    private String        remark;
    private LocalDateTime createTime;
    private BigDecimal    price;

    public Shop() {}

    public Shop(Shop value) {
        this.id = value.id;
        this.shopName = value.shopName;
        this.desc = value.desc;
        this.remark = value.remark;
        this.createTime = value.createTime;
        this.price = value.price;
    }

    public Shop(
        Integer       id,
        String        shopName,
        String        desc,
        String        remark,
        LocalDateTime createTime,
        BigDecimal    price
    ) {
        this.id = id;
        this.shopName = shopName;
        this.desc = desc;
        this.remark = remark;
        this.createTime = createTime;
        this.price = price;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getShopName() {
        return this.shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Shop (");

        sb.append(id);
        sb.append(", ").append(shopName);
        sb.append(", ").append(desc);
        sb.append(", ").append(remark);
        sb.append(", ").append(createTime);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
